theme: jekyll-theme-slate

title: Change Title
description: Change Description

colors:
  primary: #E55E4F;
  color-red: #E55E4F;
  color-green: #59A893;
  color-yellow: #F7D763;

logo:
  logo: logo.jpg

enable_fixed_header: true
